


const BALANCE_CAR = 'BALANCE_CAR';
const DELETE_GOOD = 'DELETE_GOOD';
const CHANGE_COUNTS = 'CHANGE_COUNTS';
const CLEAR_CART = 'CLEAR_CART';

export { BALANCE_CAR,CHANGE_COUNTS, DELETE_GOOD,CLEAR_CART }